// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller, onError;

  onError = function(error) {
    return console.log(error);
  };

  controller = function(scope) {
    var onSuccess, query, userRating;
    userRating = Parse.Object.extend("UserRating");
    query = new Parse.Query(userRating);
    scope.entities = [];
    onSuccess = function(data) {
      console.log(data);
      scope.entities = data;
      return console.log(scope.entities.length);
    };
    return query.find({
      success: onSuccess,
      error: onError
    });
  };

  angular.module("tapwalkdevApp").controller("MainCtrl", ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
