// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var config, rootController;

  config = function($routeProvider, $compileProvider) {
    Parse.initialize("WSGMmizuVjklAI6SpdIMBypeDCzKPUAo05QpWUnV", "OVNmBrjWj4ggScDNvKf159pVQM89vyNTlRIOIh4u");
    return $routeProvider.when("/", {
      templateUrl: "views/main.html",
      controller: "MainCtrl"
    }).otherwise({
      redirectTo: "/"
    });
  };

  angular.module("tapwalkdevApp", ['ngRoute']).config(config);

  rootController = function(root, location) {
    root.go = function(url) {
      return location.path('/' + url);
    };
    if (Parse.User.current()) {
      return root.user = Parse.User.current();
    } else {
      return root.user = null;
    }
  };

  app.run(['$rootScope', '$location', rootController]);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
