// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var app, config, rootController;

  config = function($routeProvider, $compileProvider) {
    Parse.initialize("xAONBeHiD8bBeKSdpRExCDCEbQWY8gENyPO0hP5q", "pwxKwWdssyPJf2bA7WvIFJ6mvQeGFCgtqGTbns0m");
    return $routeProvider.when("/venue/:venue/from/:from/to/:to/refresh/:refresh/pagination/:pagination", {
      templateUrl: "views/main.html",
      controller: "MainCtrl"
    });
  };

  app = angular.module("tapwalkdevApp", ['ngRoute', 'ngTable']);

  app.config(config);

  rootController = function(root, location) {
    root.go = function(url) {
      return location.path('/' + url);
    };
    if (Parse.User.current()) {
      return root.user = Parse.User.current();
    } else {
      return root.user = null;
    }
  };

  app.run(['$rootScope', '$location', rootController]);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
