// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope) {
    scope.complete = Math.floor(scope.rate);
    scope.empty = 5 - Math.ceil(scope.rate);
    scope.partial = Math.round((scope.rate - scope.complete) * 10) * 10;
    return scope.starOf = function(rate) {
      return "http://tapwalk.com/leaderboard/star_" + rate + ".png";
    };
  };

  angular.module('tapwalkdevApp').directive('rate', function() {
    return {
      templateUrl: 'views/rate.html',
      restrict: 'E',
      scope: {
        rate: '=value'
      },
      controller: ['$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=rate.map
*/
